chainguard-images/actions

apko-snapshot/README.md, apko-snapshot/action.yaml
Needs: https://github.com/chainguard-dev/actions/pull/26
=> Add keyless signing to apko-snapshot

apko-build/README.md, apko-build/action.yaml
- add a apko build action
will be used in here https://github.com/distroless/template/pull/5
=> add apko build action

apko-snapshot/README.md, apko-snapshot/action.yaml
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
=> Propagate digest output upward.

apko-snapshot/action.yaml
- add option to set the registry and update cosign
=> add option to set the registry and update cosign 

apko-build/action.yaml
- update apko to use release v0.3.3
=> update apko to use release v0.3.3

apko-snapshot/action.yaml, vul-scans/README.md, vul-scans/action.yaml
- Moves scanning into its own action
- Adds  Trivy, Snyk, and Grype Scans as well as cosign attestation for all.
=> Add Trivy, Snyk and Grype Scans

tag/README.md, tag/action.yaml
=> Add tag action for discovering and adding additional tags

vul-scans/action.yaml
=> testing cue policy validation

vul-scans/action.yaml
=> set it up so docker login is optional

apko-snapshot/action.yaml, vul-scans/action.yaml
Added the ability to sign/attest from nonpublic sigstore instances.
=> Cosign update

vul-scans/action.yaml
=> need --force for gha

tag/action.yaml
=> Specify chainguard-images repo for checking out tag action

tag/action.yaml
=> Do not change directory in tag action

tag/action.yaml
cc @priyawadhwa 
error:
```
/home/runner/work/_temp/b4966c24-4427-4838-af7f-26dab701b1e6.sh: line 2: ./tag: Is a directory
```
=> Do not change directory in tag action (hotfix)

tag/main.go
=> tag action: warn on digest failure rather than failing

tag/main.go
closes https://github.com/chainguard-images/actions/issues/43
cc @jdolitsky
=> Add exclude-tags flag to tag script

tag/action.yaml
=> Add excluded-tags input to tag action

apko-publish/action.yaml, apko-snapshot/action.yaml
=> use the new org

apko-publish/action.yaml, apko-snapshot/action.yaml
related to https://github.com/chainguard-dev/apko/pull/405
=> Add support for new version tag flags

apko-publish/action.yaml
Reverts chainguard-images/actions#79
=> Revert "Use latest apko image (from HEAD)"

apko-publish/action.yaml
Reverts chainguard-images/actions#80
=> Revert "Revert "Use latest apko image (from HEAD)""

apko-publish/action.yaml
Reverts chainguard-images/actions#81
=> Revert "Revert "Revert "Use latest apko image (from HEAD)"""

apko-publish/action.yaml
yo dawg i heard you like reverts so i reverted your revert 4 times
=> Revert "Revert "Revert "Revert "Use latest apko image (from HEAD)""""

apko-publish/action.yaml
Reverts chainguard-images/actions#83
=> Revert "Revert "Revert "Revert "Revert "Use latest apko image (from HEAD)"""""

apko-publish/action.yaml
Reverts chainguard-images/actions#84
=> Revert "Revert "Revert "Revert "Revert "Revert "Use latest apko image (from HEAD)""""""

apko-publish/action.yaml
Reverts chainguard-images/actions#85
=> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Use latest apko image (from HEAD)"""""""

apko-publish/action.yaml
=> Use latest apko image (from HEAD)

apko-build/action.yaml, apko-publish/action.yaml, apko-snapshot/action.yaml
Related to https://github.com/chainguard-images/images/issues/187
=> Add support for apko build options

apko-snapshot/action.yaml
I've tested this in both a public and private repo
=> Add slsa-attest option on apko snapshot to run slsa-generator-container

apko-build/action.yaml, apko-publish/action.yaml
The apko image built on Wednesday April 26
=> Temporarily pin apko image

apko-build/action.yaml, apko-publish/action.yaml
Reverts chainguard-images/actions#100
=> Revert "Temporarily pin apko image"

apko-build/action.yaml, apko-publish/action.yaml, apko-snapshot/action.yaml
:gift: This exposes an option that allows downstream users to specify the `apko` image to use.
This enables downstream users to pin their `apko` version directly.
/kind feature
=> Feature: Expose an option to let downstream workflows specify apko image.

apko-build/action.yaml, apko-publish/action.yaml, apko-snapshot/action.yaml
Support was added to apko here: https://github.com/chainguard-dev/apko/pull/703
=> Add support for appending packages.

apko-build/README.md, apko-build/action.yaml, apko-publish/action.yaml, apko-snapshot/README.md, apko-snapshot/action.yaml
See https://github.com/chainguard-dev/apko/pull/942
=> Remove unknown flags reflecting apko flags cleanup

apko-build/action.yaml, apko-publish/action.yaml, apko-snapshot/action.yaml
Closes #137
- Update actions to use `wolfi-dev/sdk `
=> fix: update wolfi-dev/apko to wolfi-dev/sdk

apko-publish/README.md
=> apko-publish/: explain how to use multiple tags

apko-publish/action.yaml
working as expected now, see example https://github.com/cpanato/testing-ci-providers/actions/runs/12389974960
=> remove touch

scan-apk/action.yaml
- update grype-scan to v6.0.0
- update Grype to v0.86.1
- https://github.com/anchore/scan-action/releases
=> update grype-scan action to v6.0.0

.github/chainguard/release-actions.sts.yaml, .github/workflows/release.yaml, .goreleaser.yml
same thing we did here: https://github.com/chainguard-dev/actions/pull/535
=> add release job
