chainguard-images/actions

- apko-snapshot/action.yaml
`cosign-installer` doesn't take a `version` param, which causes a warning in https://github.com/distroless/static/runs/5608554205?check_suite_focus=true#step:4:7
I believe as-is it ends up using the default cosign version param, which is [currently `1.6.0`](https://github.com/sigstore/cosign-installer/blob/b4f55743d10d066fee1de1cf0fa26069700c0195/action.yml
> Correctly specify cosign version

- apko-snapshot/action.yaml
This annotates the commit SHA, and the GitHub Actions workflow run number and attempt (in case of re-runs)
> Include annotations in signature

- apko-snapshot/action.yaml
With 0.3.1 Trivy is able to recognize that we're an Alpine image:
```
2022-04-13T23:40:25.809Z	INFO	Need to update DB
2022-04-13T23:40:25.809Z	INFO	Downloading DB...
2022-04-13T23:40:27.895Z	INFO	Detected OS: alpine
2022-04-13T23:40:27.895Z	INFO	Detecting Alpine vulnerabilities...
2022-04-13T23:40:27.896Z	INFO	Number of language-specific files: 0
```
This change will make it so that all of the distroless releases will scan the image (you can control whether this is fatal with `trivy-exit-code: '0'`.
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
> Start to scan all distroless images with Trivy

- apko-snapshot/action.yaml
Currently, we always target `:latest` and produce an ambiguous date-based tag.
With this change, `:latest` is the default and the date-based tags will be prefixed with `:latest-`, but this behavior can be overridden to target `:foo` and `:foo-` prefixed instead or in addition.
My hope with this is to better support producing multiple flavors of images from a single repo, e.g. a `:root` image from `distroless/git` to ease the Tekton transition (building from something like `.apko-root.yaml`.
> Add a `target-tag` input to control the tag we produce.

- apko-build/README.md
- apko-build/action.yaml
- apko-snapshot/README.md
- apko-snapshot/action.yaml
See https://github.com/chainguard-dev/apko/pull/210
Probably need to hold merge until there is a new apko release? Then again it is not used by default
> Add support for new --use-docker-mediatypes flag

- apko-build/action.yaml
Looks like Github actions doesn't support using inputs for the image name.
Error from https://github.com/distroless/template/runs/7148670181?check_suite_focus=true:
```
Error: distroless/actions/main/apko-build/action.yaml (Line: 34, Col: 11):
Error: distroless/actions/main/apko-build/action.yaml (Line: 34, Col: 11): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.apko-image
```
> Pin apko image to latest commit

- apko-build/action.yaml
- apko-publish/README.md
- apko-publish/action.yaml
- apko-snapshot/action.yaml
- use canary image that have a fix for the retry logic
- move action `chainguard-dev/actions/apko-build` to here and call it `distroless/actions/apko-publish`
> Use canary image and move `chainguard-dev/actions/apko-build`

- apko-build/action.yaml
Added keys and archs to build input.
Also changed to use canary version.
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>
> Make build inputs match publish.

- vul-scans/action.yaml
As-is these aren't disabling Snyk for me with:
```yaml
- uses: distroless/actions/vul-scans@main
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ github.token }}
image: ${{ matrix.ref }}
RUN_SNYK: "false"
```
I'm going to try with this change.
> Change the way we predicate steps

- apko-snapshot/action.yaml
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
> Now that digest is singular, sign using `${{ inputs.image_refs }}`

- vul-scans/action.yaml
Until Grype supports arm variants, we need a way to turn it off, so I added a toggle for all of the scanners.
> Allow eliding any of the scans, not just snyk

- apko-snapshot/action.yaml
The default value for `image_refs` was `/tmp/apko.images`, which wouldn't be visible after the `apko` step because it is executed inside of a container.
This changes it to a workspace-relative path, which is volume mounted in and shared with the rest of the workflow.
> Make the default value of `image_refs` shared with docker action.

- apko-snapshot/action.yaml
Cosign v1.8.0 panics when verifying keyless signatures, due to a recent TUF metadata change.
> Update cosign dep to v1.9.0

- apko-build/action.yaml
- apko-publish/action.yaml
- apko-snapshot/action.yaml
Without this, demo code etc. is pretty much forced to use `@local /github/workspace/packages` in apko config, vs something like `@local /work/packages` which is much easier to support (considering apko/melange images treat `/work` as default work dir)
> Enable usage of /work directory in apko config

- vul-scans/action.yaml
For testing if vul count, in the output it is helpful if the default is 0 not n/a. 
To make this work
```bash
if: ${{ steps.scans.outputs.TRIVY_COUNT != '0' || steps.scans.outputs.GRYPE_COUNT != '0' || steps.scans.outputs.SNYK_COUNT != '0'  }}
```
> changing default output to 0 even if not scanned

- vul-scans/action.yaml
If releasing and pushing an image is done in a separate step from scanning, cosign will fail without docker login, this will force it by default. 
> making docker login true by default

- apko-publish/action.yaml
- apko-snapshot/action.yaml
If nothing is passed, I just assume that the name of the repo is the package we want to search for (this should work for`distroless/go` or `distroless/nginx` or `distroless/git`, and maybe more). If it fails no biggie, nothing happens!
> Add support for --package-version-tag to apko-snapshot and apko-publish

- tag/action.yaml
Adds a step to the `tag` action which will:
1. search for any alpine version tags (for example `1.18.4-r2` for `go`
2. trim the `-r2` off of the tag
3. compare the remaining tag `1.18.4` against dockerhub and add any additional matching tags
> Trim alpine version tags and retag

- apko-publish/action.yaml
- apko-snapshot/action.yaml
This is needed to support the glibc variant images.
> Add support for apko --tag-suffix feature.

- apko-publish/action.yaml
```
Jan 19 00:11:15.367 [INFO] [arch:x86_64] finished building filesystem in /tmp/apko-239103982/x86_64
Error: failed to build layer image for "arm64": open /tmp/apko-239103982/aarch64/bin/busybox: no such file or directory
2023/01/19 00:11:15 error during command execution: failed to build layer image for "arm64": open /tmp/apko-239103982/aarch64/bin/busybox: no such file or directory
```
> Pin apko for image builds

- vul-scans/action.yaml
Just locking the digest on the forked action and linking to PR
> Temporarily point to fork of anchore/scan-action (lock digest)

- apko-publish/action.yaml
Updates the apko-publish action to use apko 0.6.1, which pulls in the cosign v2 changes.
cc @eddiezane
> apko-publish: bump to using apko 0.6.1

- apko-publish/action.yaml
Reverts chainguard-images/actions#88
> Revert "apko-publish: bump to using apko 0.6.1"

- apko-publish/action.yaml
Reverts chainguard-images/actions#90
Errors reported with images using busybox, `find` cannot be found.  Sounds like scriptlets aren't working with latest apko changes.  We use scriptlets in wolfi for busybox and glibc.  Rolling back for now to finx images.
> Revert "Use latest apko image (from HEAD)"

- apko-snapshot/action.yaml
We have made changes to `apko` to compute the "build date epoch" based on `MAX(installed packages builddate)`, which should make the image timestamp a reflection of the last time one of the packages contributing to the image changed.
This should result in significantly less nightly churn from image rebuilds where only the timestamp changes.
> This stops passing "now" as the `SOURCE_DATE_EPOCH` to `apko`.

- apko-publish/action.yaml
I did this for build already, and forgot we have two.
ref: https://github.com/chainguard-images/actions/pull/113
> Disable the VCS URL by default (for publish)

- apko-build/action.yaml
- apko-publish/action.yaml
The `--debug` flag was removed as part of https://github.com/chainguard-dev/apko/pull/1011. This PR updates the build and publish actions to leverage the new `--log-level` flag instead.
Fixes: https://github.com/chainguard-images/actions/issues/130
> replace removed --debug flag with --log-level

- apko-snapshot/action.yaml
- update to docker/login-action v3.3.0
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
> fix docker/login-action node.js deprecation warning

- apko-snapshot/action.yaml
- update docker/setup-qemu-action to v3.2.0
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
> fix docker/setup-qemu-action node.js deprecation warning

- apko-publish/action.yaml
- apko-snapshot/action.yaml
Hey 👋🏻
This pull request basically allows to provide custom OCI annotations to be added to the final artifacts (using either `apko-publish` or `apko-snapshot` actions).
If we want to add annotations without these changes, we likely need to use a separate action to update the config file before calling `apko-publish` (or `apko-snapshot`) (see [example](https://github.com/hpedrorodrigues/images/blob/e692419f263697f3ae97418ded436ffc391d660e/.github/workflows/publish.yml#L35-L43)) or implement some other workaround. The main idea here is to make this process easier.
- `apko-publish`: this version worked well [here](https://github.com/hpedrorodrigues/images/blob/06e805cea68b238bde5c297ecaf4436219b80d2c/.github/workflows/publish.yml#L41-L47) (see …
> Allow to provide custom OCI annotations

- vul-scans/action.yaml
- https://github.com/anchore/grype/issues/1102
- https://github.com/anchore/grype/pull/1104
- https://github.com/anchore/scan-action/pull/212
Revert eead431
This will also fix the last `set-output::` warning messages during action run
> Return to anchore/scan-action, issues fixed

- apko-build/action.yaml
- apko-publish/action.yaml
- apko-snapshot/action.yaml
Hey 👋🏻 
The distinction between build-time and runtime repositories was introduced in `apko` a few months ago (see [v0.15.0](https://github.com/chainguard-dev/apko/releases/tag/v0.15.0)).
This pull request basically allows us to set build-time repositories in `apko-build`, `apko-publish`, and `apko-snapshot` actions.
For more details, please see:
- https://github.com/chainguard-dev/apko/pull/1169
- https://github.com/chainguard-dev/apko/issues/1107
> Add support to set repositories for pulling packages at build time
